### ISSUE TITLE
Use PPO+Selfplay to train，the results were pretty bad

### ISSUE THREAD

**Issue by Jackory** [ToruOwO/multiagent-competition-envs#1]
Hello~ 
Have you tried to use RL algorithm to train this env?
I have tried to use **PPO+Selfplay** to **train sumo-ants-v0** and **sumo-humans-v0**, but the results were pretty bad.
The ants don't move at all, and the humans cannot stand. 
Have you encountered such problems?

Thanks！

**Comment by P1G3s** [comment]
mine was pretty bad too, did you fix it? i haven't seen anybody sucessfully replicate the results from that paper yet.

**Comment by ToruOwO** [comment]
Hi! Unfortunately the short answer is no -- I believe the original results were obtained by training with some pretty huge batch size and a fair amount of time, so I haven't been able to reproduce them.
